//TODO ml: SquareVerifier is generated by zokrates classroom, need to test if it works
// TODO ml: copy boilerplate from ERC721 tests

// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
//TODO ml: define the verifier contract that was generated by zokrates classroom
//TODO ml: only 2 test cases

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof
